spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/pagamento_db
    url: ${MYSQL_URL}
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: false
  application:
    name: pagamento

server:
  port: 8081