# exemplo deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentdeployment
  labels:
    app: paymentdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentdeployment
  template:
    metadata:
      labels:
        app: paymentdeployment
    spec:
      containers:
        - name: payment
          image: carlaccp/pagamento-techchallenge
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: MYSQL_URL