apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: "pagamento_db"
        - name: MYSQL_USER
          value: "payment"
        - name: MYSQL_PASSWORD
          value: "payment"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"